#!/usr/bin/env bash
# Change user to nginx user and default port to 8080
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Update the default site configuration to listen on port 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
